import Head from 'next/head'
// import { Inter } from 'next/font/google'
import SearchableTable from '../components/SearchableTable'
// const inter = Inter({ subsets: ['latin'] })
// import TestTable from '../components/TestTable'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <main>
    <SearchableTable/>

    {/* <TestTable/> */}
   </main>
    </>
  )
}
